"""add relationship classification columns to conflicts

Revision ID: f3a8ae9b7add
Revises: a82fa18357a9
Create Date: 2026-07-12 19:21:03.325949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3a8ae9b7add'
down_revision: Union[str, Sequence[str], None] = 'a82fa18357a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conflicts', sa.Column('relationship_type', sa.Text(), nullable=True))
    op.add_column('conflicts', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('conflicts', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conflicts', 'confidence_score')
    op.drop_column('conflicts', 'explanation')
    op.drop_column('conflicts', 'relationship_type')
    # ### end Alembic commands ###
