"""Reusable mapped-column mixins shared across ORM models.

Every entity table in 001_schema.sql follows the same three conventions:
a UUID primary key generated by the database, `created_at`/`updated_at`
audit timestamps, and (with the sole exception of the append-only
`audit_logs` table) a `deleted_at` soft-delete marker. These mixins keep
that repetition out of the individual model files.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import TIMESTAMP


class UUIDPrimaryKeyMixin:
    """UUID primary key, generated by Postgres via `gen_random_uuid()`."""

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at` audit timestamps.

    `updated_at` is bumped by the `set_updated_at()` database trigger
    (see 001_schema.sql), not by the ORM — application code should never
    assign it directly.
    """

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class SoftDeleteMixin:
    """`deleted_at` soft-delete marker.

    Excluding soft-deleted rows from a query (`WHERE deleted_at IS NULL`)
    is a repository-layer concern, not enforced by the model itself, so
    these classes remain usable for both normal and admin/audit reads.
    """

    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True, default=None
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
